#! /bin/sh
sxhkd &
#picom &
flameshot &
nm-applet &
lxsession &
nitrogen --restore &
$HOME/.config/polybar/launch.sh


#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d '' '' '' '' '' '' '' ''


bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#808080"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Assigning workspaces
bspc rule -a "Code" desktop='^2'
bspc rule -a "kdenlive" desktop='^5'





